return {
  { "ellisonleao/gruvbox.nvim", priority = 1000, palette_overriders = { dark0_hard = "#1d2021" } },
  { "rebelot/kanagawa.nvim" },
  { "shatur/neovim-ayu" },
  { "tanvirtin/monokai.nvim" },
  { "aditya-azad/candle-grey" },
  { "neanias/everforest-nvim" },
  { "olivercederborg/poimandres.nvim" },
  { "elvessousa/sobrio" },
  { "projekt0n/github-nvim-theme" },
  -- { "mcchrish/zenbones.nvim" },
  { "ramojus/mellifluous.nvim" },
  { "nyoom-engineering/oxocarbon.nvim" },
  { "yorickpeterse/vim-paper" },
  { "n1ghtmare/noirblaze-vim" },
  { "kadekillary/skull-vim" },
  { "chriskempson/base16-vim" },
  { "kvrohit/rasmus.nvim" },
  { "morhetz/gruvbox" },
  { "NLKNguyen/papercolor-theme" },
  { "bignimbus/pop-punk.vim" },
  { "rose-pine/neovim" },
  {"itchyny/lightline.vim"},
{'akinsho/bufferline.nvim', version = "*", dependencies = 'nvim-tree/nvim-web-devicons'},
}
