theme = "autumn_night"


[editor]
# gutters = ["diagnostics", "spacer", "diff"]
gutters = ["spacer"]
end-of-line-diagnostics = "hint"
true-color = true
color-modes = true

[editor.search]
smart-case = false # case sensitive search

[editor.statusline]
left = ["mode", "spinner"]
# center = ["file-name"]
center = ["file-absolute-path"]
# right = ["diagnostics", "position", "position-percentage", "file-encoding", "file-type"]
right = ["diagnostics", "position", "position-percentage", "file-encoding", "file-type"]
separator = ">"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "VISUAL"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

# [editor.indent-guides]
# render = true
# character = "╎" # Some characters that work well: "▏", "┆", "┊", "⸽"
# skip-levels = 1

[editor.soft-wrap]
enable = true

[editor.inline-diagnostics]
cursor-line = "warning" # show warnings and errors on the cursorline inline
